# -*- coding: utf-8 -*-
"""seaborn 1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12JaCa7yBFI_J2-krTuC8a_lGT3WWdQd9
"""

import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd

df= pd.read_csv("realistic_sales_dataset.csv")

sns.relplot(data=df, x="price",y="sales")
plt.show()

sns.lineplot(data=df, x="order_date",y="sales")
plt.xticks(rotation=45)
plt.show

sns.barplot(data=df, x="category",y="sales")
plt.show()

sns.countplot(data=df, x="payment_mode")
plt.xticks(rotation=45)
plt.show()

sns.boxplot(data=df, x="category",y="sales")
plt.show

sns.violinplot(data=df, x="category",y="sales")
plt.show()

sns.histplot(data=df, x="sales",bins=30)
plt.show()

corr=df.corr(numeric_only= true)
sns.heatmap(corr, annot=True, cmap="coolwarm")
plt.show()

sns.pairplot(df[["price","quantity","discount","sales"]])
plt.show()

